name: link_life_one
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3

  cupertino_icons: ^1.0.2
  check_points: ^0.0.1+1
  intl: ^0.17.0
  http:
  flutter_session_manager: ^1.0.3
  shared_preferences: ^2.0.15
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  flutter_screenutil: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  date_format: ^2.0.4
  json_to_model: ^2.3.0
  json_serializable: ^6.0.1
  test: ^1.16.5
  dalocale: ^2.0.0
  build_runner: ^2.0.6
  auto_size_text: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: LinotteBold
      fonts:
        - asset: assets/fonts/LinotteBold.ttf
    - family: LinotteSemiBold
      fonts:
        - asset: assets/fonts/LinotteSemiBold.ttf
  assets:
    - assets/images/
